spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: keven
    password: keven123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

  ai:
    model:
      chat: DeepSeek-R1  # <-- FALTAVA ESSA LINHA
    azure:
      openai:
        api-key: EO4QYkYu6S9TslvPXHA4fAmqwS1bdwYn74FS3ZonE02RBuN8qipnJQQJ99BEACfhMk5XJ3w3AAAAACOGjlDk
        endpoint: https://mr553-mak5nrtw-swedencentral.cognitiveservices.azure.com/
        chat:
          options:
            deployment-name: DeepSeek-R1
            temperature: 0.7
            api-version: 2025-05-12  # <-- ESSA LINHA TAMBÉM ESTAVA FALTANDO


api:
  security:
    jwt:
      secret: your_secret_key_here



logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http.client: DEBUG